# 1. Create a 3x3x3 array with random values 

In [6]:
import numpy as np
np.random.rand(3,3,3)

array([[[0.11725778, 0.46308063, 0.03126416],
        [0.56969181, 0.01624044, 0.40838438],
        [0.4833783 , 0.30298287, 0.3235987 ]],

       [[0.91159849, 0.95239043, 0.40546039],
        [0.59860989, 0.24181111, 0.19827022],
        [0.98882471, 0.37848968, 0.29796439]],

       [[0.80650197, 0.9757611 , 0.87660675],
        [0.14438561, 0.43790214, 0.67576166],
        [0.67852705, 0.85081299, 0.48097446]]])

In [ ]:
# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [31]:
a= np.array([[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0]])
a[1][0]= 1
a[2][1]= 2
a[3][2]= 3
a[4][3]= 4
a


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [43]:
a=  np.array([[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0]])
a
i=0
j=0
for i in range(0,8):
    for j in range(0,8):
        if ((i+j)%2==0):
            a[i][j]=1
        else:
            a[i][j]=0
a


array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

# 4. Normalize a 5x5 random matrix

In [54]:
x= np.random.rand(5,5)
x
xmax, xmin = x.max(), x.min()
print("After normalization:")
x= (x - xmin)/(xmax - xmin)
x

After normalization:


array([[0.93722946, 0.33667218, 0.44559183, 0.59596559, 0.20650915],
       [1.        , 0.25020191, 0.83069788, 0.09196675, 0.69172648],
       [0.34485865, 0.66485509, 0.        , 0.0603474 , 0.77344576],
       [0.91109509, 0.23066263, 0.32993047, 0.50301952, 0.25631288],
       [0.57459622, 0.5852298 , 0.09675781, 0.04222305, 0.77591041]])

# 5.  How to find common values between two arrays?

In [56]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))



Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [59]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-29
Today:  2020-07-30
Tomorrow:  2020-07-31


# 7. Consider two random array A and B, check if they are equal

In [66]:
a= np.random.rand(3,3)
b=np.random.rand(3,3)
print(a, b)
b
c= np.eye(5,5)
d= np.eye(5,5)
print(c,d)
equal1 = np.array_equal(a,b)
equal2 = np.array_equal(c,d)
print(equal1,equal2)


[[0.10117403 0.3499841  0.26173373]
 [0.97595426 0.23007963 0.86901148]
 [0.96091207 0.39291042 0.45852756]] [[0.72123056 0.99205807 0.93660499]
 [0.51942941 0.1895473  0.21745626]
 [0.01731258 0.23232382 0.1546393 ]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
False True


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [69]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.71046541 0.38537027 0.09540592 0.26301971 0.77340236 0.77950907
 0.         0.54026529 0.01732917 0.63691211]


# 9. How to print all the values of an array?

In [70]:
Z = np.eye(3,3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 10.Subtract the mean of each row of a matrix

In [74]:
X = np.random.rand(3, 3)

# Recent versions of numpy
Y = X - X.mean(axis=1)

# Older versions of numpy
Y1 = X - X.mean(axis=1)

print(Y)
print(Y1)

[[-0.32695421  0.54880594 -0.36366743]
 [-0.35576965  0.36010343 -0.83050195]
 [ 0.45398206  0.70115019 -0.18714839]]
[[-0.32695421  0.54880594 -0.36366743]
 [-0.35576965  0.36010343 -0.83050195]
 [ 0.45398206  0.70115019 -0.18714839]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [75]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[4. 1. 3. 5. 2. 4. 1. 2. 5. 3.]


# 12.How to get the diagonal of a dot product?

In [76]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(A)
print(B)
# Slow version
prod1=np.diag(np.dot(A, B))

# Fast version
prod2=np.sum(A * B.T, axis=1)

print("diagonal of a dot product method 1 is....",prod1)
print("diagonal of a dot product method 2 is....",prod2)

[[0.40418454 0.79922914 0.82074774 0.71790014 0.59724194]
 [0.72077578 0.74146732 0.62265267 0.77022791 0.74361933]
 [0.64532659 0.8709577  0.78699755 0.86222944 0.06159943]
 [0.00705215 0.19817787 0.20783523 0.73020122 0.4561417 ]
 [0.12477811 0.43094398 0.51135124 0.74747281 0.59597911]]
[[0.73275988 0.88928778 0.372225   0.89127603 0.04178705]
 [0.59248027 0.9426613  0.70007142 0.86603772 0.78621697]
 [0.17732662 0.15401186 0.71290673 0.1270797  0.1155107 ]
 [0.97421915 0.58061831 0.04068535 0.81435113 0.62406967]
 [0.23994891 0.67417521 0.84205111 0.00334005 0.60546035]]
diagonal of a dot product method 1 is.... [1.75793774 2.38436368 1.49794511 0.80049028 1.23041294]
diagonal of a dot product method 2 is.... [1.75793774 2.38436368 1.49794511 0.80049028 1.23041294]


# 13.How to find the most frequent value in an array?

In [77]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[9 8 8 0 7 8 0 9 9 5 2 6 4 0 6 8 9 5 4 0 7 1 4 4 7 1 1 6 4 5 5 9 3 6 5 0 1
 4 4 3 0 6 4 2 6 8 9 5 9 3]
4


# 14.How to get the n largest values of an array

In [78]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5


print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


# 15.How to create a record array from a regular array?

In [79]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
